/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TaskManagementSystem;

import DatabaseConnection.registerUserCon;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TaskManagementSystem.DashboardMain;
import static TaskManagementSystem.DashboardMain.dashboardTable;
import static TaskManagementSystem.DashboardMain.date1;
import static TaskManagementSystem.DashboardMain.taskId;
import static TaskManagementSystem.TaskInfo.setValue;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Bisma
 */
public class TaskInfo extends javax.swing.JFrame {

    /**
     * Creates new form TaskInfo
     */
    DefaultTableModel model;
    
    
    public static void setValue(){
        int row = dashboardTable.getSelectedRow();
        taskCategoryLabel.setText(dashboardTable.getModel().getValueAt(row, 0).toString());
        taskNameLabel.setText(dashboardTable.getModel().getValueAt(row, 1).toString());
        deadlineLabel.setText(dashboardTable.getModel().getValueAt(row, 2).toString());
        statusLabel.setText(dashboardTable.getModel().getValueAt(row,3).toString());
        taskPriorityLabel.setText(dashboardTable.getModel().getValueAt(row, 4).toString());
        descriptionLabel.setText(dashboardTable.getModel().getValueAt(row, 5).toString());
        idField.setText(dashboardTable.getModel().getValueAt(row, 6).toString());
    }
    
    public TaskInfo() {
        initComponents();
        setTitle("Task Information");
        // set the form in the middle 
        this.setLocationRelativeTo(null);
        setValue();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        taskCategoryLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        taskNameLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deadlineLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        taskPriorityLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        editTaskPageBtn2 = new javax.swing.JPanel();
        editTaskBtnText2 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        deleteBtnLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JPanel();
        cancelBtnLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/taskInfo.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Task Information");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Task Category :");

        taskCategoryLabel.setBackground(new java.awt.Color(102, 102, 102));
        taskCategoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taskCategoryLabel.setText("Task Category Value");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Task Name : ");

        taskNameLabel.setBackground(new java.awt.Color(102, 102, 102));
        taskNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taskNameLabel.setText("Task Name Value");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Deadline : ");

        deadlineLabel.setBackground(new java.awt.Color(102, 102, 102));
        deadlineLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deadlineLabel.setText("Deadline Value");

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Status : ");

        statusLabel.setBackground(new java.awt.Color(102, 102, 102));
        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusLabel.setText("Status Value");

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Task Priority : ");

        taskPriorityLabel.setBackground(new java.awt.Color(102, 102, 102));
        taskPriorityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        taskPriorityLabel.setText("Task Priority value");

        descriptionLabel.setBackground(new java.awt.Color(102, 102, 102));
        descriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionLabel.setText("Description Value");

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Description :");

        editTaskPageBtn2.setBackground(new java.awt.Color(210, 240, 255));
        editTaskPageBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editTaskPageBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editTaskPageBtn2MouseClicked(evt);
            }
        });

        editTaskBtnText2.setBackground(new java.awt.Color(51, 102, 255));
        editTaskBtnText2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        editTaskBtnText2.setForeground(new java.awt.Color(51, 102, 255));
        editTaskBtnText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editTaskBtnText2.setText("Edit Task");
        editTaskBtnText2.setAutoscrolls(true);
        editTaskBtnText2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editTaskBtnText2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editTaskBtnText2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editTaskPageBtn2Layout = new javax.swing.GroupLayout(editTaskPageBtn2);
        editTaskPageBtn2.setLayout(editTaskPageBtn2Layout);
        editTaskPageBtn2Layout.setHorizontalGroup(
            editTaskPageBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editTaskBtnText2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );
        editTaskPageBtn2Layout.setVerticalGroup(
            editTaskPageBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTaskPageBtn2Layout.createSequentialGroup()
                .addComponent(editTaskBtnText2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        deleteBtn.setBackground(new java.awt.Color(246, 208, 208));
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        deleteBtnLabel.setBackground(new java.awt.Color(153, 233, 244));
        deleteBtnLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        deleteBtnLabel.setForeground(new java.awt.Color(237, 56, 56));
        deleteBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBtnLabel.setText("Delete Task");
        deleteBtnLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteBtnLayout = new javax.swing.GroupLayout(deleteBtn);
        deleteBtn.setLayout(deleteBtnLayout);
        deleteBtnLayout.setHorizontalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteBtnLayout.createSequentialGroup()
                .addComponent(deleteBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        deleteBtnLayout.setVerticalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteBtnLayout.createSequentialGroup()
                .addComponent(deleteBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cancelBtn.setBackground(new java.awt.Color(230, 230, 230));
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        cancelBtnLabel.setBackground(new java.awt.Color(153, 233, 244));
        cancelBtnLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cancelBtnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelBtnLabel.setText("Cancel");
        cancelBtnLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelBtnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cancelBtnLayout = new javax.swing.GroupLayout(cancelBtn);
        cancelBtn.setLayout(cancelBtnLayout);
        cancelBtnLayout.setHorizontalGroup(
            cancelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );
        cancelBtnLayout.setVerticalGroup(
            cancelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancelBtnLayout.createSequentialGroup()
                .addComponent(cancelBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        idField.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editTaskPageBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(taskCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskPriorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(taskCategoryLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(taskNameLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(deadlineLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(taskPriorityLabel))
                .addGap(49, 49, 49)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel)
                .addGap(18, 18, 18)
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editTaskPageBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editTaskBtnText2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTaskBtnText2MouseClicked
        // Display the edit task
        EditTask editTaskUi= new EditTask();
        editTaskUi.setVisible(true);
        
        // copy all the data from the table to the edit task page
        try{
            EditTask.taskCategoryField.setText(taskCategoryLabel.getText());
            EditTask.taskNameField.setText(taskNameLabel.getText());
            
            // get string from Task Info Form
            String date = deadlineLabel.getText();
            
            // convert string into date
            try {
                date1 = new SimpleDateFormat("yyyy-mm-dd").parse(date);
                System.out.println(date1);
                EditTask.deadlineDateField.setDate(date1);
            } catch (ParseException ex) {
                Logger.getLogger(DashboardMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            EditTask.taskPriorityDropDown.setSelectedItem(taskPriorityLabel.getText());
            EditTask.statusDropDown.setSelectedItem(statusLabel.getText());
            EditTask.descriptionTextArea.setText(descriptionLabel.getText());
            EditTask.taskIdField.setText(idField.getText());

        } catch (Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_editTaskBtnText2MouseClicked

    private void editTaskPageBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTaskPageBtn2MouseClicked
        // Display the edit task
        EditTask editTaskUi= new EditTask();
        editTaskUi.setVisible(true);
    }//GEN-LAST:event_editTaskPageBtn2MouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // Delete the data if some data is clicked

        int row = DashboardMain.dashboardTable.getSelectedRow();
        Statement ps;

        // check if a row is selected
        int taskIdTable = Integer.parseInt(idField.getText());
        String deleteQuery = "DELETE FROM `task_list` WHERE `task_list`.`task_id` = " + taskIdTable;
        try {
            ps = registerUserCon.getConnection().createStatement();
            ps.executeUpdate(deleteQuery);
            JOptionPane.showMessageDialog(null, "Task Deleted! Please refresh to update data!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Unable to delete");
        }
            

            
//        } catch (Exception e){
//            JOptionPane.showMessageDialog(null, "Unable to delete");
//            System.out.println(e);
//        }

    }//GEN-LAST:event_deleteBtnMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // Close form 
        dispose();

    }//GEN-LAST:event_cancelBtnMouseClicked

    private void cancelBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnLabelMouseClicked
        // Close the form 
        dispose();
        
    }//GEN-LAST:event_cancelBtnLabelMouseClicked

    private void deleteBtnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnLabelMouseClicked
        // Delete action
        
         // Delete the data if some data is clicked
        
        int row = dashboardTable.getSelectedRow();
        Statement ps;
        
        // check if a row is selected
        if(row >= 0){
            try{
                int taskIdTable = Integer.parseInt(dashboardTable.getModel().getValueAt(row, 6).toString());
                String deleteQuery = "DELETE FROM `task_list` WHERE `task_list`.`task_id` = " + taskIdTable;
                ps = registerUserCon.getConnection().createStatement();
                ps.executeUpdate(deleteQuery);
                
                // update ui 
                model.removeRow(row);
                JOptionPane.showMessageDialog(null, "Task Deleted!");
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Task Deleted!");
                System.out.println(e);
            }
        } 
            
        
    }//GEN-LAST:event_deleteBtnLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelBtn;
    private javax.swing.JLabel cancelBtnLabel;
    public static javax.swing.JLabel deadlineLabel;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JLabel deleteBtnLabel;
    public static javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel editTaskBtnText2;
    private javax.swing.JPanel editTaskPageBtn2;
    public static javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel statusLabel;
    public static javax.swing.JLabel taskCategoryLabel;
    public static javax.swing.JLabel taskNameLabel;
    public static javax.swing.JLabel taskPriorityLabel;
    // End of variables declaration//GEN-END:variables

    private void assertEquals(String rawString, String utf8EncodedString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
